module.exports = [
  {
    seq: 0,
    route: "testFunction",
    text: "Test Function",
    file: "testFunction",
  },
  {
    seq: 1,
    route: "significantDigits",
    text: "Significant Digits",
    file: "basic/significantDigits",
  },
  {
    seq: 2,
    route: "convertDensity",
    text: "Converting Densities",
    file: "convert/convertDensity",
  },
  {
    seq: 3,
    route: "convertDistance",
    text: "Converting Distances",
    file: "convert/convertDistance",
  },
  {
    seq: 4,
    route: "convertMass",
    text: "Converting Mass",
    file: "convert/convertMass",
  },
  {
    seq: 5,
    route: "convertVolume",
    text: "Converting Volume",
    file: "convert/convertVolume",
  },
  {
    seq: 6,
    route: "density",
    text: "Density",
    file: "basic/density",
  },
  {
    seq: 7,
    route: "densitywp",
    text: "Density Word Problem",
    file: "basic/densitywp",
  },
  {
    seq: 8,
    route: "massMoles",
    text: "Mass, Moles, GFW",
    file: "moles/massMoles",
  },
  {
    seq: 9,
    route: "elementsMolesMass",
    text: "Elements, Moles, and Mass",
    file: "moles/elementsMolesMass",
  },
  {
    seq: 10,
    route: "moleswp",
    text: "Moles word problems",
    file: "moles/moleswp",
  },
  {
    seq: 11,
    route: "electronsProtonsNeutrons",
    text: "Protons, Electrons, and Neutrons",
    file: "atoms/electronsProtonsNeutrons",
  },
  {
    seq: 12,
    route: "quantumNumbersWp",
    text: "Quantum Numbers Word Problems",
    file: "quantum/quantumNumbersWp",
  },
  {
    seq: 13,
    route: "molarity",
    text: "Molarity",
    file: "moles/molarity",
  },
  {
    seq: 14,
    route: "massVolumeMolarityWp",
    text: "Mass, Volume, and Molarity word problem",
    file: "moles/massVolumeMolarityWp",
  },
  {
    seq: 15,
    route: "osomoticPressure",
    text: "Osomotic Pressure",
    file: "basic/osomoticPressure",
  },
  {
    seq: 16,
    route: "freezingBoilingPoints",
    text: "Freezing and Boiling Points of Aqueous Solutions",
    file: "basic/freezingBoilingPoints",
  },
  {
    seq: 17,
    route: "formulaMassCalculations",
    text: "Chemical Formulas and Mass Calculations",
    file: "basic/formulaMassCalculations",
  },
  {
    seq: 18,
    route: "massFormulaWp",
    text: "Mass and Mole Relationships in Chemical Formulas",
    file: "basic/massFormulaWp",
  },
  {
    seq: 19,
    route: "balancing",
    text: "Balancing Reactions",
    file: "reactions/balancing",
  },
  {
    seq: 20,
    route: "reactionMassesWp",
    text: "Stoichiometry - Mass Relationships",
    file: "reactions/reactionMassesWp",
  },
  {
    seq: 21,
    route: "reactionPercentsWp",
    text: "Stoichiometry - Percent Yield",
    file: "reactions/reactionPercentsWp",
  },
  {
    seq: 22,
    route: "limitingReagentsWp",
    text: "Limiting reagents",
    file: "reactions/limitingReagentsWp",
  },
  {
    seq: 23,
    route: "reactionCombinedWp",
    text: "Combining limiting reagents and percentage yield",
    file: "reactions/reactionCombinedWp",
  },
  {
    seq: 24,
    route: "avogadrosLaw",
    text: "Avogadro's Law",
    file: "basic/avogadrosLaw",
  },
  {
    seq: 25,
    route: "boylesLaw",
    text: "Boyle's Law",
    file: "basic/boylesLaw",
  },
  {
    seq: 26,
    route: "charlesLaw",
    text: "Charles's Law",
    file: "basic/charlesLaw",
  },
  {
    seq: 27,
    route: "combinedGasLaw",
    text: "Combined Gas Law",
    file: "basic/combinedGasLaw",
  },
];
