name: deploy api to lambda
on: [push]
jobs:
  deploy_lambdas:
    name: deploy lambda
    strategy:
      matrix:
        node-version: [14.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Install node_modules in /routes
        run: npm install
        working-directory: ./routes

      - name: Zip routes
        run: zip -r routes.zip . -x routes.zip -x *.test.js -x testHandler.js
        working-directory: ./routes

      - name: zipinfo
        run: zipinfo routes.zip
        working-directory: ./routes

      - name: deploy lambda api
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1
          function_name: api
          zip_file: ./routes/routes.zip
